
url: "https://alexbishop.github.io"
baseurl: ""

title: Alex Bishop
short-title: Alex
subtitle: Research Website

description: A pure maths PhD student at the University of Technology Sydney. Studying topics in group theory and computer science.

navbar-links:
  Papers: "/papers"
  Conferences: "/conferences"
  Research: "/research"

avatar: "/assets/image/profile.jpg"

author:
  name: Alex Bishop

social-network-links:
#  rss: true
  email: "alexbishop1234@gmail.com"
  orcid: "0000-0001-6803-1143"
  arxiv: "bishop_a_2"
  researchgate: "Alex_Bishop7"
  github: alexbishop
  twitter: alexbishop1234

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Output options
timezone: "Australia/Sydney"
markdown: kramdown
highlighter: rouge
permalink: "/blog/post/:year-:month-:day-:title/"
paginate_path: "/blog/page:num/"
paginate: 5

design:
  ms-tile-color: "#e9ecef"
  theme-color: "#e9ecef"
  background-color: "#e9ecef"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true
      include-social-meta: true
      prefix-site-title: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show-avatar: false
      comments: true
      social-share: true
      prefix-site-title: false

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - node_modules
  - build_tmp
  - scripts
  - src
  - package.json
  - package-lock.json

sass:
    style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-avatar

